### ISSUE TITLE
Kagami Kira's data

### ISSUE THREAD

**Issue by TBNV999** [Speculative/hodllive#1]
Unfortunately, Kagami Kira has graduated. So do you keep his channel's data intact or remove it from this repository?

**Comment by Speculative** [comment]
Thank you for pointing that out! I will plan to keep his (and any other graduating member's) channel data here for historical purposes as long as I am able to. Do you think keeping it would be inappropriate?

**Comment by TBNV999** [comment]
No, keeping it is better. Thanks!
